app/models.py
# 3rd party imports
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# local imports
from app import db, login_manager

class User(UserMixin, db.Model):
    """
    Create a User table
    """

    # Ensures the table name as following
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)

    
    @property
    def password(self):
        """
        Prevent password from being accessed
        """
        raise AtributeError('password is not a readable atribute')


    @password.setter
    def password(self, password):
        """
        Set password to be a hashed password
        """
        self.password_hash = generate_password_hash(password)


    def verify_password(self, password):
        """
        Check if hashed password matches acutal password
        """
        return check_password_hash(self.password_hash, password)


    def __repr__(self):
        return '<User: {}>'.format(self.username)


    #Set up user_loader
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

app/home/forms.py
from flask_wtf import Form
from wtforms import StringField, IntegerField
from wtforms.validators import InputRequired


class FlickrForm(Form):
    api_key = StringField('API KEY', validators=[InputRequired()])
    image_limit = IntegerField('Image Limit', validators=[InputRequired()])


class WeatherForm(Form):
    api_key = StringField('API KEY', validators=[InputRequired()])
    location = StringField('Location', validators=[InputRequired()])

app/__init__.py
# 3rd part imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

# local imports
from config import app_config

# db var init
db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    Bootstrap(app)
    db.init_app(app)

    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page"
    login_manager.login_view = "auth.login"

    migrate = Migrate(app, db)


    from app import models

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)


    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template, redirect, url_for
from flask_login import login_required
import sqlite3
from .forms import FlickrForm, WeatherForm
import psutil
import platform
import subprocess

from . import home


@home.route('/')
def homepage():
    return render_template('home/index.html', title="Main view")


@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/widgets', methods=["POST", "GET"])
@login_required
def widgets():
    flickr_form = FlickrForm()
    conn = sqlite3.connect('/var/Databases/73fcb940d49477bf777e196445fabfda.sqlite')
    conn_cursor = conn.cursor()

    conn_cursor.execute('''SELECT * FROM flickr_config''')
    flickr_data = conn_cursor.fetchone()

    flickr_form.api_key.data = flickr_data[0]
    flickr_form.image_limit.data = flickr_data[1]

    weather_form = WeatherForm()

    conn_cursor.execute('''SELECT * FROM weather_config''')
    weather_data = conn_cursor.fetchone()

    weather_form.api_key.data = weather_data[0]
    weather_form.location.data = weather_data[1]

    conn_cursor.close()
    conn.close()

    return render_template('home/widgets.html', title="Widgets Configuration", flickr_form=flickr_form,
                           weather_form=weather_form)


@home.route('/widgets/flickr', methods=["POST"])
@login_required
def widget_flickr():
    flickr_form = FlickrForm()

    conn = sqlite3.connect('/var/Databases/73fcb940d49477bf777e196445fabfda.sqlite')
    conn_cursor = conn.cursor()

    if flickr_form.validate_on_submit():
        conn_cursor.execute('''SELECT count(*) as total FROM flickr_config''')
        result = conn_cursor.fetchone()
        total = result[0]

        if total > 0:
            conn_cursor.execute('''UPDATE flickr_config SET api_key = ?, image_limit = ?''', (flickr_form.api_key.data,
                                                                                              flickr_form.image_limit.data))
        else:
            conn_cursor.execute('''INSERT INTO flickr_config (api_key, image_limit) VALUES(?,?)''', (flickr_form.api_key.data,
                                                                                                    flickr_form.image_limit.data))
    conn.commit()
    conn_cursor.close()
    conn.close()

    return redirect(url_for('home.widgets'))


@home.route('/widgets/weather', methods=["POST"])
@login_required
def widget_weather():
    weather_form = WeatherForm()

    conn = sqlite3.connect('/var/Databases/73fcb940d49477bf777e196445fabfda.sqlite')
    conn_cursor = conn.cursor()

    if weather_form.validate_on_submit():
        conn_cursor.execute('''SELECT count(*) as total FROM weather_config''')
        result = conn_cursor.fetchone()
        total = result[0]

        if total > 0:
            conn_cursor.execute('''UPDATE weather_config SET api_key = ?, location = ?''', (weather_form.api_key.data,
                                                                                              weather_form.location.data))
        else:
            conn_cursor.execute('''INSERT INTO weather_config (api_key, location) VALUES(?,?)''',
                                (weather_form.api_key.data,
                                 weather_form.location.data))
    conn.commit()
    conn_cursor.close()
    conn.close()

    return redirect(url_for('home.widgets'))

# Get network interfaces details
def get_inet():
    inetaddr = psutil.net_if_addrs()
    inet_det = []
    for k, v in inetaddr.iteritems():
        if v[0][0] == 2:
            inet_det.append([k, v[0][1], v[0][2], v[0][3]])

    return inet_det

def get_uptime():
    raw = subprocess.check_output('uptime').replace(',','')
    days = int(raw.split()[2])
    if 'min' in raw:
        hours = 0
        minutes = int(raw[4])
    else:
        hours, minutes = map(int,raw.split()[4].split(':'))

    return "%d days, %d:%d" % (days, hours, minutes)

@home.route('/system')
@login_required
def system():
    memt = psutil.virtual_memory().total
    mema = psutil.virtual_memory().active
    memi = psutil.virtual_memory().inactive
    cpu = psutil.cpu_percent()
    arch = platform.processor()
    hostname = platform.node()
    kernel = platform.release()
    inet = get_inet()
    uptime = get_uptime()

    # Preparing memory lists
    mpoint = [p.mountpoint for p in psutil.disk_partitions()]
    mpointperc = [psutil.disk_usage(z).percent for z in [k for k in mpoint]]
    mpointuse = zip(mpoint, [psutil.disk_usage(z).percent for z in [k for k in mpoint]], mpointperc)

    return render_template('home/system.html', title="System Stats", cpu=cpu, memt=memt, mema=mema, memi=memi, mpointuse=mpointuse, inet=inet, uptime=uptime, kernel=kernel, hostname=hostname, arch=arch)

app/templates/base.html
<!-- app/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} {{ title }} {% endblock%} - Smart Mirror Configuration Panel</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Project Dream Team</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a></li>
                  {% else %}
                    <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                  {% endif %}
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li class="footer-menu-divider">&sdot;</li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/dashboard.html
{% extends 'base.html' %}

{% block body %}
<div class="intro-header">

</div>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            {% block menu %}
                {% include 'home/menu.html' %}
            {% endblock %}
        </div>

        <div class="col-sm-9">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Welcome to the Smart Mirror</h1>
                    <h3>Configuration Panel</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/menu.html
<div class="panel panel-default sidebar-menu">
    <div class="panel-heading">Menu</div>
        <div class="panel-body">
            <ul class="menu-items">
                <li><a href="{{ url_for('home.dashboard') }}">Home</a></li>
                <li><a href="{{ url_for('home.widgets') }}">Widgets Configuration</a></li>
                <li><a href="{{ url_for('home.system') }}">System Overview</a></li>
            </ul>
        </div>
</div>

app/templates/home/system.html
{% extends 'home/dashboard.html' %}

{% block content %}
<div class="panel panel-default ">
     <div class="panel-heading">Operating system details</div>
     <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-xs-2">
            Hostname
            </div>
            <div class="col-xs-2">
                {{ hostname }}
            </div>
          </div>
          <div class="row">
            <div class="col-xs-2">
            Architecture 
            </div>
            <div class="col-xs-2">
                {{ arch }}
            </div>
          </div>
          <div class="row">
            <div class="col-xs-2">
            Kernel version
            </div>
            <div class="col-xs-2">
                {{ kernel }}
            </div>
          </div>
          <div class="row">
            <div class="col-xs-2">
            Uptime
            </div>
            <div class="col-xs-2">
                {{ uptime }}
            </div>
          </div>
        </div>
     </div>
 </div>

     <div class="panel-heading">Stats</div>
     <div class="panel-body">
        <div class="container">

          <div class="row">
            <div class="col-xs-2">
              CPU usage 
            </div>
            <div class="col-xs-2">
                {{ cpu }}%
            </div>
          </div>

          <br>
          Memory
          <div class="row">
            <div class="col-xs-2">
              Total
            </div>
            <div class="col-xs-2">
                {{ memt // 1024 // 1024 }} GB
            </div>
          </div>

          <div class="row">
            <div class="col-xs-2">
              Used
            </div>
            <div class="col-xs-2">
                {{ mema // 1024 // 1024 }} GB
            </div>
          </div>

          <div class="row">
            <div class="col-xs-2">
              Free
            </div>
            <div class="col-xs-2">
                {{ memi // 1024 // 1024 }} GB
            </div>
          </div>

        <br>
        Free disk space
        {% for item1, item2, item3 in mpointuse %}
          <div class="row">
            <div class="col-xs-2">
             {{ item1 }}
            </div>
            <div class="col-xs-2">
                {{ item2 }} GB
            </div>
            <div class="col-xs-2">
                {{ item3 }} %
            </div>
          </div>
        {% endfor %}

        </div>
     </div>
 </div>
{% endblock %}

app/templates/home/widgets.html
{% extends 'home/dashboard.html' %}

{% block content %}
<div class="panel panel-default widget">
     <div class="panel-heading">Flickr</div>
     <div class="panel-body">
         <form method="post" action="{{ url_for('home.widget_flickr') }}">
             <div class="form-group">
                 {{ flickr_form.api_key.label}}: {{ flickr_form.api_key(class_='form-control') }}
                 {{ flickr_form.image_limit.label}}: {{ flickr_form.image_limit(class_='form-control') }}
                 {{ flickr_form.csrf_token }}
             </div>

             <button type="submit" class="btn btn-default">Save</button>
         </form>
     </div>
 </div>

<div class="panel panel-default widget">
     <div class="panel-heading">Weather</div>
     <div class="panel-body">
         <form method="post" action="{{ url_for('home.widget_weather') }}">
             <div class="form-group">
                 {{ weather_form.api_key.label}}: {{ weather_form.api_key(class_='form-control') }}
                 {{ weather_form.location.label}}: {{ weather_form.location(class_='form-control') }}
                 {{ weather_form.csrf_token }}
             </div>

             <button type="submit" class="btn btn-default">Save</button>
         </form>
     </div>
 </div>
{% endblock %}